/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(autocorrelate.h) */
/* BINDTOOL_HEADER_FILE_HASH(9a0a2a6a048b0cf211b583823d1dcde9) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <doa/autocorrelate.h>
// pydoc.h is automatically generated in the build directory
#include <autocorrelate_pydoc.h>

void bind_autocorrelate(py::module &m) {

  using autocorrelate = ::gr::doa::autocorrelate;

  py::class_<autocorrelate, gr::block, gr::basic_block,
             std::shared_ptr<autocorrelate>>(m, "autocorrelate",
                                             D(autocorrelate))

      .def(py::init(&autocorrelate::make), py::arg("inputs"),
           py::arg("snapshot_size"), py::arg("overlap_size"),
           py::arg("avg_method"), D(autocorrelate, make))

      ;
}
